[package]
name = "genshin_check_in"
version = "1.2.0"
edition = "2021"

[dependencies]
ureq = { version = "2", features = ["json", "cookies"] }
cookie_store = "0.16"
url = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
simple_logger = "4"

[profile.release]
lto = "fat"
codegen-units = 1
