name: build

on: [workflow_dispatch, push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Init rust compiler
        run: |
          rustup toolchain install stable --profile minimal
          rustup target add x86_64-unknown-linux-gnu

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: |
          cargo update
          RUSTFLAGS='-C target-feature=+crt-static' cargo b -r --target x86_64-unknown-linux-gnu

      - name: Post build process
        run: |
          chmod 755 target/x86_64-unknown-linux-gnu/release/genshin_check_in
          cp target/x86_64-unknown-linux-gnu/release/genshin_check_in server
          ls -lh

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: genshin_check_in
          path: |
            server
            index.py
